### PR TITLE
update badge urls, remove wrong test info

### PR DESCRIPTION
**Pull request by ChristophWurst**
cc @MorrisJobke @LukasReschke @GitHubUser4234

### CODE REVIEW

**Comment by ChristophWurst** [comment]
wow. Scrutinizer has been blocked for more than 1h now. I wonder why we're having so many reports on it, I guess the server repos is causing that.

**Comment by MorrisJobke** [comment]
> wow. Scrutinizer has been blocked for more than 1h now. I wonder why we're having so many reports on it, I guess the server repos is causing that.

It looks like it's already waiting over 90 minutes for the code coverage data in the other job :(

**Comment by MorrisJobke** [comment]
https://scrutinizer-ci.com/g/nextcloud/twofactor_totp/inspections/2029cd19-6d90-47f9-99f8-44717635a394

**Comment by ChristophWurst** [comment]
Right, the build did not generate the coverage data. https://travis-ci.org/nextcloud/twofactor_totp/jobs/173869317#L969

**Comment by MorrisJobke** [comment]
I canceled that build and now it works 👍

**Pull request merged**
