### PR TITLE
add simple app icon

### LINKED ISSUE #129: Icon for TOTP provider app
Sadly I have no real idea what an icon could look like, but maybe @eppfel or @skjnldsv  or any other in @nextcloud/designers has an idea.

Then we could also use this in the personal settings (see nextcloud/server#3151) as sidebar icon.

cc @ChristophWurst

### PR DESCRIPTION
**Pull request by ChristophWurst**
cc @skjnldsv @MorrisJobke @eppfel let me know what you think :-)

This image is not optimized yet, but I will run it through the fancy script we have in server if the design has been approved.

fixes #129

### CODE REVIEW

**Comment by ChristophWurst** [comment]
bildschirmfoto von 2017-01-25 20-16-15

**Comment by MariusBluem** [comment]
Making the key inside of the phone horizontal and bitter would make it more visible (especially in case of using as small icon on personal-settings page) 😁

**Comment by eppfel** [comment]
Jep, turn the key. Maybe diagonal is enough. And remove the small dot in the bottom and the bar in the top. They are too fine.

**Comment by skjnldsv** [comment]
Agree with the key. Too thin! :)
Good though!

**Comment by ChristophWurst** [comment]
Thanks everyone for your feedback!

I've update the icon. Now it looks like this:

bildschirmfoto von 2017-02-05 22-04-48

@eppfel as you can see I have removed the thin bar at the top. However, I did not remove the dot on the bottom, but made it a bigger instead. Without it, it's hard to recognize the icon IMO, it looks like a framed key:
bildschirmfoto von 2017-02-05 22-05-20

**Comment by ChristophWurst** [comment]
@MariusBluem thanks! As soon as @skjnldsv and @eppfel gave their 👍 too I can optimize the icon and merge this 🚀

**Comment by skjnldsv** [comment]
👍 😆

**Pull request merged**
