### PR TITLE
Do not test against stable11 because it's incompatible

### PR DESCRIPTION
**Pull request by ChristophWurst**
@rigrig easy to review :)

### CODE REVIEW

**Comment by rigrig** [comment]
I'm not really familiar with Travis, but I think that commit also drops the only test against sqlite, is that ok?

And it looks like the selenium tests failed while waiting for the checkbox to appear at https://github.com/nextcloud/twofactor_totp/blob/master/tests/Acceptance/TOTPAcceptanceTest.php#L99

**Comment by ChristophWurst** [comment]
> , but I think that commit also drops the only test against sqlite, is that ok?

Good catch. That was not my intention. Will fix this tomorrow :-)

**Comment by ChristophWurst** [comment]
All tests passed 🚀 

@rigrig @MorrisJobke please (re)review :-)

**Comment by ChristophWurst** [comment]
@rigrig thanks for your review! I've added you as collaborator so that your GitHub review unlocks the merge button :-)

**Pull request merged**
