### PR TITLE
Release 1.4.0

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Changelog should contain everything from https://github.com/nextcloud/twofactor_totp/compare/1.3.1...master
* Added [Krankerl](https://github.com/christophwurst/krankerl) packaging config

Package for testing:
[twofactor_totp.tar.gz](https://github.com/nextcloud/twofactor_totp/files/1552321/twofactor_totp.tar.gz)

### CODE REVIEW

**Comment by tacruc** [comment]
Ok works fine on current master. Downloaded the tar.gz file.

- [ ] enabed the app
- [ ] enabled 2FA for a user
- [ ] Relogged in

**Comment by ChristophWurst** [comment]
Just so that we're talking about the same: what master did you use? The server master + the tarball I provided? Or this app's master branch?

**Comment by tacruc** [comment]
Servers master (actually to be more precies I used https://github.com/tacruc/server/tree/GPG-Email) + the tarball. But this branch is up to changes in the email system the master branch.

**Comment by ChristophWurst** [comment]
Perfect! Will publish to the app store tomorrow.

**Comment by natebrink** [comment]
I just updated to NC13 today and received the message that it was disabled because it was not compatible with 13. I tried to re-enable it in the app store and received the same message. Is there something different that has to be done for 13?

**Comment by rigrig** [comment]
The app version that is compatible with NC13 is incompatible with NC12, which means it wasn't updated while you were running NC12.
So after updating Nextcloud, you have to update the app, and then you can re-enable it.

**Comment by natebrink** [comment]
Got it. That makes sense. I'm still learning the ropes with NC. Thank you for the help.

**Pull request merged**
