### PR TITLE
[WIP] Build tests again master and stable and update to nc 13

### LINKED ISSUE #179: Fix builds
See discussion here https://github.com/nextcloud/twofactor_u2f/issues/58#issuecomment-314378402

### PR DESCRIPTION
**Pull request by Hanzei**
- [x] Build against stable12 and master
- [x] Add support for nc 13
- [ ] Fix UI tests

Fixes #179

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Unrelated to the changes here but acceptance tests fail with nc13

**Comment by ChristophWurst** [comment]
> Fix acceptance tests

Almost 😉 

```
There was 1 error:

1) OCA\TwoFactorTOTP\Tests\Acceptance\TOTPAcceptenceTest::testEnableTOTP

Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"partial link text","selector":"src="/settings/img/personal.svg"}

  (Session info: chrome=59.0.3071.86)

  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1 x86_64)

/home/travis/build/nextcloud/core/apps/twofactor_totp/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:102

/home/travis/build/nextcloud/core/apps/twofactor_totp/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:321

/home/travis/build/nextcloud/core/apps/twofactor_totp/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:597

/home/travis/build/nextcloud/core/apps/twofactor_totp/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:190

/home/travis/build/nextcloud/core/apps/twofactor_totp/tests/Acceptance/TOTPAcceptanceTest.php:89
```

**Comment by Hanzei** [comment]
@ChristophWurst Is there a test server with runs the current master branch, which I can use to test stuff?

**Comment by ChristophWurst** [comment]
> @ChristophWurst Is there a test server with runs the current master branch, which I can use to test stuff?

You can easily set up a local Nextcloud installation based on the current master branch: https://docs.nextcloud.com/server/12/developer_manual/general/devenv.html

**Comment by Hanzei** [comment]
@ChristophWurst I set up a development environment and installed twofactor_totp. But there seems to be a bug which keeps me from working on this. I reported it [here](https://github.com/nextcloud/twofactor_totp/issues/177#issuecomment-324285720)

**Comment by ChristophWurst** [comment]
@Hanzei I've integrated most of your changes in other PRs. Thanks a lot!

**Pull request closed without merging**
