### PR TITLE
[stable27] Fix npm audit

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated fix of npm audit

### CODE REVIEW

**Comment by st3iny** [comment]
CI fix at https://github.com/nextcloud/twofactor_totp/pull/1468.

**Comment by blizzz** [comment]
moving to 27.1.7

**Comment by blizzz** [comment]
```
Error: 

Vue packages version mismatch:

- vue@2.7.16 (/home/runner/work/twofactor_totp/twofactor_totp/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.14 (/home/runner/work/twofactor_totp/twofactor_totp/node_modules/vue-template-compiler/package.json)
```

**Comment by ChristophWurst** [comment]
The bot undid my fixes.

**Comment by skjnldsv** [comment]
Moving to 26.0.13

**Review by st3iny — APPROVED** [review]
Tested and works.

**Comment by skjnldsv** [comment]
You were fast :rocket: 
Thanks @st3iny !!

**Pull request merged**
