### PR TITLE
exclude unneeded assets from QR-Code package

### PR DESCRIPTION
**Pull request by My1**
see #346

### CODE REVIEW

**Comment by My1** [comment]
by the way do we actually need things like the .git folder or the js.map in the 2.0.1 release package? 

while we are already cleaning everything up, it wouldnt be a bad chance to talk about that stuff as well.

image

**Comment by ChristophWurst** [comment]
> by the way do we actually need things like the .git folder

No, that one should be removed as well :+1: 

> js.map

That one should remain. It will help debug js errors as it maps compressed scripts to source scripts.

**Comment by My1** [comment]
but do we need debug stuff in the final release? I mean debug stuff makes sense during dev but in the release, I am not totally sure.

**Comment by ChristophWurst** [comment]
> but do we need debug stuff in the final release? I mean debug stuff makes sense during dev but in the release, I am not totally sure.

Yes! if users report an error and it says "line 50303" I have *no clue* what source line this was caused by. The stack traces are practically useless. With source maps, browsers translate these traces to readable ones.

**Comment by My1** [comment]
okay, makes sense.

**Pull request merged**
