### PR TITLE
Enable TOTP checkbox gets ticked even if its not enabled successfully.

### PR DESCRIPTION
**Pull request by theronakpatel**
## Summary

Enable TOTP checkbox gets check marked even if we cancel enabling it. And hitting the ticked checkbox again results in endless loop. Reloading the page in any case shows the correct unchecked behavior.

## The problem

- login to nextcloud
- Click Avatar on the top right and go to `Settings` >> `Security`
- Under Two Factor Authentication, Hit the enable TOTP checkbox
- Click cross on the `Authentication required` popup to cancel enabling the checkbox
- User receives Could not enable TOTP notification but the checkbox is shown as ticked
- Now Try unchecking the checkbox which will result it in endless loading.
- Now reload the page so it shows the box unchecked as desired.

<How one can reproduce the issue>

**What is the current behavior?**

User receives Could not enable TOTP notification but the checkbox is shown as ticked, until the next reload of the page.

<What actually happens>

**What is the expected correct behavior?**

If Enabling TOTP fails the checkbox should remain unchecked. And ticked only when TOTP is successfully enabled.

<What you should see instead>

**Relevant screenshots**

Screenshot_from_2022-07-12_15-06-42

<Add the labels corresponding to your issue by adding a tilde and typing the name of the label you think apply to your issue in the line above. You need to type a tilde before the name of each label you want to apply to the issue.>

Screenshot_2022-10-25_at_15 58 19

Screenshot_2022-10-25_at_15 58 30

### CODE REVIEW

**Comment by theronakpatel** [comment]
## Summary

Enable TOTP checkbox gets check marked even if we cancel enabling it. And hitting the ticked checkbox again results in endless loop. Reloading the page in any case shows the correct unchecked behavior.

## The problem

- login to nextcloud
- Click Avatar on the top right and go to `Settings` >> `Security`
- Under Two Factor Authentication, Hit the enable TOTP checkbox
- Click cross on the `Authentication required` popup to cancel enabling the checkbox
- User receives Could not enable TOTP notification but the checkbox is shown as ticked
- Now Try unchecking the checkbox which will result it in endless loading.
- Now reload the page so it shows the box unchecked as desired.


<How one can reproduce the issue>

**What is the current behavior?**

User receives Could not enable TOTP notification but the checkbox is shown as ticked, until the next reload of the page.

<What actually happens>

**What is the expected correct behavior?**

If Enabling TOTP fails the checkbox should remain unchecked. And ticked only when TOTP is successfully enabled.

<What you should see instead>

**Relevant screenshots**

Screenshot_from_2022-07-12_15-06-42


<Add the labels corresponding to your issue by adding a tilde and typing the name of the label you think apply to your issue in the line above. You need to type a tilde before the name of each label you want to apply to the issue.>

Screenshot_2022-10-25_at_15 58 19

Screenshot_2022-10-25_at_15 58 30

**Review by ChristophWurst — APPROVED** [review]
Nice catch!

**Comment by ChristophWurst** [comment]
Please run `npm run build`` and commit the changes in `js/`.

And please sign-off your commit

**Comment by ChristophWurst** [comment]
Please squash your commits into one signed-off commit and we're good to go :)

**Comment by theronakpatel** [comment]
Hey @ChristophWurst I squashed the commits, but now I can see 6 files with the changes. Strangely l10n folders shows changes!

**Comment by theronakpatel** [comment]
@ChristophWurst I am closing this MR and created new https://github.com/nextcloud/twofactor_totp/pull/1317 to resolve issues. Please validate and review / merge it.

**Pull request closed without merging**
