### PR TITLE
[stable26] Fix npm audit

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated fix of npm audit

### CODE REVIEW

**Comment by blizzz** [comment]
moving to 26.0.9

**Comment by st3iny** [comment]
CI fix at https://github.com/nextcloud/twofactor_totp/pull/1466.

**Comment by blizzz** [comment]
needs  a rebase or recreate?

**Comment by blizzz** [comment]
moving to 26.0.11

**Comment by blizzz** [comment]
Node tests are still failing. Please take care @ChristophWurst @st3iny

**Comment by blizzz** [comment]
moving to 26.0.12

**Comment by blizzz** [comment]
```
Error: 

Vue packages version mismatch:

- vue@2.7.16 (/home/runner/work/twofactor_totp/twofactor_totp/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.14 (/home/runner/work/twofactor_totp/twofactor_totp/node_modules/vue-template-compiler/package.json)
```

**Review by st3iny — APPROVED** [review]
Tested and works.

**Pull request merged**
