### PR TITLE
Add missing translations to pt_BR

### PR DESCRIPTION
**Pull request by jsalatiel**
Add missing translations to pt_BR

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Hi :wave: 

thanks a lot for helping with the translations. We actually don't put the into our code directly but manage them via https://www.transifex.com/nextcloud/nextcloud/dashboard/. Please sign up there and enter your strings. They will be sync'ed to this repository automatically :)

**Comment by jsalatiel** [comment]
Hi @ChristophWurst, I am trying to understand how to add new strings in transiflex. The strings that I have added in this patch are not listed. I can add the msgid and the msgstr, but I do not know what these files and line numbers mean:

image

**Comment by ChristophWurst** [comment]
Oh okay so the problem is actually that we fail to extract the string from the code. That is why it's missing on Transifex. Good catch!

This seems similar to https://github.com/nextcloud/mail/issues/2530, where we are facing the same problem. I have to dig deeper and check our extraction tool.

**Comment by jsalatiel** [comment]
The file containing the string is this : twofactor_totp/js/main-login-setup.js

**Pull request closed without merging**
