### PR TITLE
Update master target versions

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by PVince81** [comment]
CI fails with `Previous: PDOException: SQLSTATE[HY000]: General error: 4047 InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.`

I guess we should pin the MariaDB version like it's been done in other PRs.

I'll take care

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
- [ ] requires https://github.com/nextcloud/twofactor_totp/pull/1157

**Comment by nickvergessen** [comment]
> requires Update version on master #1157

Ready to rebase

**Pull request merged**
